version: '3'

services:
    product-services121:
        build: './products'
        volumes:
            - ./products:/usr/src/app
        ports:
            - 5000:5000
        environment:
            - PYTHONUNBUFFERED:1